ref https://jakevdp.github.io/PythonDataScienceHandbook/02.02-the-basics-of-numpy-arrays.html

# Load Numpy library

In [42]:
import numpy
numpy.__version__

'1.20.1'

## import NumPy using ``np`` as an alias:

In [43]:
import numpy as np

# The Basics of NumPy Arrays

## NumPy Array Attributes

First let's discuss some useful array attributes.
We'll start by defining three random arrays, a one-dimensional, two-dimensional, and three-dimensional array.
We'll use NumPy's random number generator, which we will *seed* with a set value in order to ensure that the same random arrays are generated each time this code is run:

In [44]:
import numpy as np
np.random.seed(0)  # seed for reproducibility, just for the below codes

# Examples of 1-D, 2-D, 3-D arrays
x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array

print(type(x1))
print(type(x2))
print(type(x3))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


Each array has attributes ``ndim`` (the number of dimensions), ``shape`` (the size of each dimension), and ``size`` (the total size of the array):

In [45]:
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60


Another useful attribute is the ``dtype``

In [46]:
print("dtype:", x3.dtype)
print("dtype for x1:", x1.dtype)

dtype: int64
dtype for x1: int64


## Array Indexing: Accessing Single Elements
### similar to list structure

If you are familiar with Python's standard list indexing, indexing in NumPy will feel quite familiar.
In a one-dimensional array, the $i^{th}$ value (counting from zero) can be accessed by specifying the desired index in square brackets, just as with Python lists:

In [47]:
x1

array([5, 0, 3, 3, 7, 9])

In [48]:
x1[0]

5

In [49]:
x1[4]

7

To index from the end of the array, you can use negative indices:

In [50]:
x1[-1] # last element

9

In [51]:
x1[-2] # second last element

7

In a multi-dimensional array, items can be accessed using a comma-separated tuple of indices:


In [52]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [53]:
x2[0, 0] # 1st component: row index, 2nd: column index

3

In [54]:
x2[2, 0]

1

In [55]:
x2[2, -1]

7

In [56]:
x2[0, 0] = 12
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [57]:
x1[0] = 3.14159  # this will be truncated!
print(x1)
print(x1.dtype)

[3 0 3 3 7 9]
int64


## Change type of an array

In [58]:
x1_float = x1.astype(float) # change type of x1 to float
print(x1.dtype)
print(x1_float.dtype)
x1_float[0] = 3.14159
print(x1_float)

int64
float64
[3.14159 0.      3.      3.      7.      9.     ]


## Array Slicing: Accessing Subarrays

Just as we can use square brackets to access individual array elements, we can also use them to access subarrays with the *slice* notation, marked by the colon (``:``) character.
The NumPy slicing syntax follows that of the standard Python list; to access a slice of an array ``x``, use this:
``` python
x[start:stop:step]
```
If any of these are unspecified, they default to the values ``start=0``, ``stop=``*``size of dimension``*, ``step=1``.
We'll take a look at accessing sub-arrays in one dimension and in multiple dimensions.

### One-dimensional subarrays

In [59]:
x = np.arange(10) # arange(n): generate array of 0,1 ,.., n-1
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
x[:5]  # first five elements

array([0, 1, 2, 3, 4])

In [61]:
x[5:]  # elements after index 5

array([5, 6, 7, 8, 9])

In [62]:
x[4:7]  # middle sub-array

array([4, 5, 6])

In [63]:
x[::2]  # every other element

array([0, 2, 4, 6, 8])

In [64]:
x[1::2]  # every other element, starting at index 1

array([1, 3, 5, 7, 9])

A potentially confusing case is when the ``step`` value is negative.
In this case, the defaults for ``start`` and ``stop`` are swapped.
This becomes a convenient way to reverse an array:

In [65]:
x[::-1]  # all elements, reversed, stepsize=-1

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [66]:
x[5::-2]  # reversed every other from index 5

array([5, 3, 1])

### Multi-dimensional subarrays

Multi-dimensional slices work in the same way, with multiple slices separated by commas.
For example:

In [67]:
print(x2)
print('x2 shape = ', x2.shape)

[[12  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]
x2 shape =  (3, 4)


In [68]:
x2[:2, :3]  # two rows, three columns

array([[12,  5,  2],
       [ 7,  6,  8]])

In [69]:
x2[:3, ::2]  # all rows, every other column

array([[12,  2],
       [ 7,  8],
       [ 1,  7]])

Finally, subarray dimensions can even be reversed together:

In [70]:
x2[::-1, ::-1]

array([[ 7,  7,  6,  1],
       [ 8,  8,  6,  7],
       [ 4,  2,  5, 12]])

#### Accessing array rows and columns

One commonly needed routine is accessing of single rows or columns of an array.
This can be done by combining indexing and slicing, using an empty slice marked by a single colon (``:``):

In [71]:
print(x2)
print(x2[:, 0])  # first column of x2

[[12  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]
[12  7  1]


In [72]:
print(x2[0, :])  # first row of x2

[12  5  2  4]


In the case of row access, the empty slice can be omitted for a more compact syntax:

In [73]:
print(x2[0])  # equivalent to x2[0, :]

[12  5  2  4]


### Subarrays as no-copy views

One important–and extremely useful–thing to know about array slices is that they return *views* rather than *copies* of the array data.
This is one area in which NumPy array slicing differs from Python list slicing: in lists, slices will be copies.
Consider our two-dimensional array from before:

In [74]:
print(x2)

[[12  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


Let's extract a $2 \times 2$ subarray from this:

In [75]:
x2_sub = x2[:2, :2]
print(x2_sub)

[[12  5]
 [ 7  6]]


Now if we modify this subarray, we'll see that the original array is changed! Observe:

In [76]:
x2_sub[0, 0] = 99
print(x2_sub)

[[99  5]
 [ 7  6]]


In [77]:
print(x2) # change value in x2_sub will change value in the original array

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


This default behavior is actually quite useful: it means that when we work with large datasets, we can access and process pieces of these datasets without the need to copy the underlying data buffer.

### Creating copies of arrays

Despite the nice features of array views, it is sometimes useful to instead explicitly copy the data within an array or a subarray. This can be most easily done with the ``copy()`` method:

In [78]:
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)

[[99  5]
 [ 7  6]]


If we now modify this subarray, the original array is not touched:

In [79]:
x2_sub_copy[0, 0] = 42
print(x2_sub_copy)

[[42  5]
 [ 7  6]]


In [80]:
print(x2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


## Reshaping of Arrays

Another useful type of operation is reshaping of arrays.
The most flexible way of doing this is with the ``reshape`` method.
For example, if you want to put the numbers 1 through 9 in a $3 \times 3$ grid, you can do the following:

In [81]:
grid = np.arange(1,10)
print(grid)
print(grid.shape) # 1D array
grid2 = grid.reshape(1, 9) # 1st component: # of rows, 2nd: # of columns
print(grid2)
print(grid2.shape)# 2D array
grid3 = grid.reshape((-1, 9)) # -1: unknown, numpy will decide
print(grid3.shape)
grid4 = grid.reshape(-1, 3) #
print(grid4)
print(grid4.shape)

[1 2 3 4 5 6 7 8 9]
(9,)
[[1 2 3 4 5 6 7 8 9]]
(1, 9)
(1, 9)
[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [82]:
grid2 = grid.reshape(-1,1)
print(grid2)
print(grid2.shape)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
(9, 1)


Note that for this to work, the size of the initial array must match the size of the reshaped array. 
Where possible, the ``reshape`` method will use a no-copy view of the initial array, but with non-contiguous memory buffers this is not always the case.

Another common reshaping pattern is the conversion of a one-dimensional array into a two-dimensional row or column matrix.
This can be done with the ``reshape`` method, or more easily done by making use of the ``newaxis`` keyword within a slice operation:

In [83]:
x = np.array([1, 2, 3])
print(x)
print(x.shape)
# row vector via reshape
new_x = x.reshape((1, 3))
print(new_x)
print(new_x.shape)

[1 2 3]
(3,)
[[1 2 3]]
(1, 3)


In [84]:
# row vector via newaxis
print(x)
print(x.shape)
y = x[np.newaxis, :]
print(y)
print(y.shape)

[1 2 3]
(3,)
[[1 2 3]]
(1, 3)


In [85]:
# column vector via newaxis
y2 = x[:, np.newaxis]
print(y2.shape)

(3, 1)


We will see this type of transformation often throughout the remainder of the book.

## Array Concatenation and Splitting

All of the preceding routines worked on single arrays. It's also possible to combine multiple arrays into one, and to conversely split a single array into multiple arrays. We'll take a look at those operations here.

### Concatenation of arrays

Concatenation, or joining of two arrays in NumPy, is primarily accomplished using the routines ``np.concatenate``, ``np.vstack``, and ``np.hstack``.
``np.concatenate`` takes a tuple or list of arrays as its first argument, as we can see here:

In [86]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
print('x=',x)
print('y=',y)
np.concatenate([x, y])

x= [1 2 3]
y= [3 2 1]


array([1, 2, 3, 3, 2, 1])

You can also concatenate more than two arrays at once:

In [87]:
z = [99, 99, 99]
print(np.concatenate([x, y, z]))

[ 1  2  3  3  2  1 99 99 99]


It can also be used for two-dimensional arrays:

In [88]:
grid = np.array([[1, 2, 3],
                 [4, 5, 6]])
print(grid.shape)

(2, 3)


In [89]:
# concatenate along the first axis
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [90]:
# concatenate along the second axis (zero-indexed)
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

## flatten array

In [91]:
grid = np.array([[1, 2, 3],
                 [4, 5, 6]])
print(grid.shape)
grid2 = grid.reshape(1,-1) #1 row, don't care # of columns
# print(grid2)
print(grid2.shape) #2-D array

grid3 = grid.ravel()
# print(grid3)
print(grid3.shape) #1-D array


(2, 3)
(1, 6)
(6,)


## matrix just n-dimensional array

# Matrix operators

In [92]:
mat1 = np.array([[1, 2, 3],
                 [4, 5, 6]])
mat2 = np.array([[2, 4, 6],
                 [1, 2, 3]])

print(mat1)
print(mat2)

[[1 2 3]
 [4 5 6]]
[[2 4 6]
 [1 2 3]]


In [93]:
print(mat1*mat2) # not a matrix multipilication

[[ 2  8 18]
 [ 4 10 18]]


In [94]:
mat3 = mat1.dot(mat2.T)
print(mat3)

[[28 14]
 [64 32]]
